### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by davecastlevania** [Chase-Bullock/Jamming#5]
Great job with this project, I really like how you were able to at least connect Spotify and successfully get search working. There was just a single bug with the Client_ID. Otherwise, after that was fixed it seems good to go. We're always available on Codecademy Pro chat to talk about React projects from 8AM - 12AM EST. I think you did a great job with the project! Keep it up!

Grade: Satisfactory

**Comment by Chase-Bullock** [comment]
I left the client_ID out because it is a security threat.
